defaults:
  - data: copy
  - _self_

seed: 42

model:
  training_mode: "normal"
  approx_inverse: false  # For forward BPTT
  hidden_dim: 64
  precision: "float32"
  T_min_frac: 1.0
  T_max_frac: 2.0
  norm_before_readout: true
  pooling: "none"
  unroll: 1

training:
  optimizer: "adamw"
  weight_decay: 0.01
  scheduler: "cosine"
  learning_rate: 3e-4
  log_every_steps: 20
  eval_frequency: 1000
  gradient_clipping: 1.0
